---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: ubuntu-10.04
  - name: centos-7.0
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
  - name: server
    run_list:
      - recipe[git::server]
    attributes:
    excludes:
      - centos-7.0  # Getting CentOS working with Git Daemon and runit is, well, kinda nuts
      - centos-6.6  # So should we leave a Platform/Suite combination lying around that we know we won't support? Naw!
